language: python
jobs:
  include:
    - name: Windows
      os: windows
      language: sh
      before_install:
        - choco install python3 --version 3.7.3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      install: python -m pip install --upgrade pip wheel pytest tox
      script:
        - tox -e py37-win
    - name: OS X
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - tox -e py37
    - name: Python37
      os: xenial
      python: "3.7"
      script:
        - tox -e py37
    - name: Python36
      os: trusty
      python: "3.6"
      script:
        - tox -e py36
    - stage: deploy
      os: trusty
      python: "3.6"
      script:
       - |
         pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
         pip install restructuredtext-lint
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        distributions: sdist bdist_wheel
        on:
          tags: true

install: pip3 install --upgrade pip wheel pytest tox

cache:
  directories:
  - $HOME/.cache/pip
